
# Urban Analytics: A Toolkit for Sustainable Urban Development.

## Notebook to practice the Python Basics

---

Dr Fernando Benitez-Paez -  University of St Andrews - School of Geography and Sustainable Development Iteration 2024-1.0

# Exercise 1:  Introduction to Markdown

* In the following Markdown cell, write your name, you student ID, your github user, and the URL of your UA repo in github.
* Insert three links to your favourite websites.
* Check this website to get all the syntax from Markdown https://www.markdownguide.org/basic-syntax/

### Info
#### Selma Christensen
#### selmachristensen
#### 180021112
#### https://github.com/selmachristensen/UARepo

---------------------------------------------

### Favorite Websites
#### https://www.nytimes.com/crosswords?campaignId=6F88R&redirect_uri=https%3A%2F%2Fwww.nytimes.com%2F
#### https://www.momondo.co.uk
#### https://www.dmi.dk


# Challenge 1: 
 Create a table with required columns and rows to represent the type of roads in the UK. The table should include headers and hiperlinks.

#### Types of roads in the UK

| street | avenue | boulevard | lane | highway | alley |
|---|---|---|---|---|---|
| [street explanation](https://en.wikipedia.org/wiki/Street)| [avenue explanation](https://en.wikipedia.org/wiki/Avenue) | [boulevard explanation](https://en.wikipedia.org/wiki/Boulevard) | [lane explanation](https://en.wikipedia.org/wiki/Lane) | [highway explanation](https://en.wikipedia.org/wiki/Highway#History) | [alley explanation](https://en.wikipedia.org/wiki/Alley) |

# Exercise 2:  Working with Variables

* Declare two variables, num1 and num2, with values 5 and 8 respectively
* Sum these variables and print the results 
* Swap the values of num1 and num2.


In [3]:
num1 = 5
num2 = 8

# Sum the previous variables and print the result. Recall how we can use the f marker to style the outcome
sum_result = num1 + num2
print(f"Sum: {sum_result}")

# Swap the values of num1 and num2. Recall how variables can be modified 
num1, num2 = num2, num1
print(f"Swapped values: num1={num1}, num2={num2}")

Sum: 13
Swapped values: num1=8, num2=5


# Challenge 2:

In the following cell, create the code to calculate the average of three numbers and print the result. There is no need for functions. Comment your code and the process.


In [6]:
num1 = 2
num2 = 3
num3 = 4

average_sum = ( num1 + num2 + num3 ) / 2

print(average_sum)

4.5


# Exercise 3: Logical Operator

Logical operators are used to combine conditional statements:

* Declare two variables, x and y, with values 10 and 20
* Check if x is greater than 5 **and** y is less than 30
* Check if either x is less than 5 **or** y is greater than 30.

In [7]:
x = 10
y = 20

# Check if x is greater than 5 and y is less than 30.
if x > 5 and y < 30:
    print("Both conditions are True.")

Both conditions are True.


In [8]:
# Check if either x is less than 5 or y is greater than 30.
if x < 5 or y > 30:
    print("At least one condition is True")

# Challenge 3:

Write a condition to check if a number is even.

In [11]:
x = 4
if x%2 == 0:
    print("the number is even")

the number is even


# Exercise 4: Loops

Loops are used to repeat a block of code.

For and While Loops:

* Use a for loop to print numbers from 1 to 5.
* Use a while loop to print even numbers from 2 to 8.
* Calculate the sum of numbers from 1 to 10 using a loop.

In [13]:
# Using a for loop to print numbers from 1 to 5.
for i in range(1, 6):
    print(f"The initial loop included: {i}")

# Using now a while loop to print even numbers from 2 to 8.
num = 2
while num <= 8:
    print(f"The second loop included: {num}")
    num += 2

# What if you need to calculate the sum of numbers from 1 to 10 using a loop.
sum_numbers = 0
for j in range(1, 11):
    sum_numbers += j
    print(f"The last loop included: {sum_numbers}")

The initial loop included: 1
The initial loop included: 2
The initial loop included: 3
The initial loop included: 4
The initial loop included: 5
The second loop included: 2
The second loop included: 4
The second loop included: 6
The second loop included: 8
The last loop included: 1
The last loop included: 3
The last loop included: 6
The last loop included: 10
The last loop included: 15
The last loop included: 21
The last loop included: 28
The last loop included: 36
The last loop included: 45
The last loop included: 55


# Challenge 4:

Write the python code  to find the factorial of a number using a loop. The factorial of a number (integer positive) is the sum of multiplication of all the integers smaller than that positive integer. For example, factorial of **5** is:

5 * 4 * 3 * 2 * 1 which equals to 120. 

How you can do that in a python script?, please try your best without using google.

In [22]:
# Using a for loop to print numbers from 1 to 5.
num = 5
factoral = 1
for i in range(1, num + 1):
    factoral *= i
    print(f" The factoral for {i} is: {factoral}")

 The factoral for 1 is: 1
 The factoral for 2 is: 2
 The factoral for 3 is: 6
 The factoral for 4 is: 24
 The factoral for 5 is: 120


# Exercise 5: If-else Statements

* Declare a variable age and check **if** it's greater than 18.
* Use **elif** to check if age is between 13 and 18.
* **If** neither condition is met, print "Age is below 13".
* Could you implement a simple **rock-paper-scissors** game using if-else statements?

In [25]:
age = int(input("Enter the age"))

# Check if the variable age is greater than 18.
if age > 18:
    print("You are an adult.")

# Use elif to check if age is between 13 and 18.
elif 13 <= age <= 18:
    print("You are a teenager.")
    # If neither condition is met, print "Age is below 13."
else:
    print("Age is below 13.")

# A simple rock-paper-scissors game using if-else statements, should be something like this

import random
#We need a random library to make a fun game againts the computer, and the code has small issue can you fixed?

player_choice = input("Enter your choice (rock, paper, or scissors): ")
choices = ["rock", "paper", "scissors"]
computer_choice = random.choice(choices)
print(f"Your choice: {player_choice}")
print(f"Computer's choice: {computer_choice}")

if player_choice == computer_choice:
    print("It's a tie!")
elif (
    (player_choice == "rock" and computer_choice == "scissors")
    or (player_choice == "paper" and computer_choice == "rock")
    or (player_choice == "scissors" and computer_choice == "paper")
    ):
    print("You win!")
else:
    print("Computer wins!")


Enter the age 12


Age is below 13.


Enter your choice (rock, paper, or scissors):  rock


Your choice: rock
Computer's choice: rock
It's a tie!


# Challenge 5:

Help me to write the python code, I can use to provide the grades based on the marks according to the following table:

| Mark   | Grade |
|--------|-------|
| 81-100 | 20    |
| 61-80  | 15    |
| 41-60  | 10    |
| 20-40  | 5     |


In [29]:
mark = int(input("Enter the mark"))

# Check if the variable mark is greater than 81.

if mark > 81:
    print("You got a 20.")

# Use elif to check if mark is between x and y.
elif 61 <= mark <= 80:
    print("You got a 15.")
elif 41 <= mark <= 60:
    print("You got a 10.")
elif 20 <= mark <= 40:
    print("You got a 5.")

# If none of the conditions are met

else:
    print("You got a 0.")

Enter the mark 79


You got a 15.


# Exercise 6: Creating Functions

Functions help modularize code by grouping related actions. A function is a block of organized, reusable code that can make your programs more effective, easier to read, and simple to manage. You can think functions as little self-contained programs that can perform a specific task that you can use repeatedly in your code. One of the basic principles in good programming is “do not to repeat yourself”. In other words, you should avoid having duplicate lines of code in your scripts. Functions are a good way to avoid such situations and they can save you a lot of time and effort as you don’t need to tell the computer repeatedly what to do every time it does a common task, such as converting temperatures from Fahrenheit to Celsius. 


* Define a function square that squares a given number.
* Use the function to calculate the square of 7.
* Write a function is_prime to check if a number is prime.
* Finish the code!

In [31]:
# Define a function square that squares a given number.
def square(number):
    return number ** 2

# Using the function!

result = square(7)
print(f"Square of 7: {result}")

# Lets create another function is_prime to check if a number is prime.
def is_prime(number):
    if number < 2:
        return False
    for i in range(2, int(number ** 0.5) + 1):
        if number % i == 0:
            return False
    return True

# Finish the code here calling the function and adding the input to let the user provide the number.

Square of 7: 49


# Challenge 6:

* Write and use a function to convert Fahrenheit to Celsius. Use the input parameter to let the user enter a number in Fahrenheit and then get the correspondant value in Celsius
* Go to https://www.w3schools.com/python/exercise.asp?filename=exercise_functions1 and complete the 6 excersices. Functions are a very important part of Python so we will use extra time to practice that.


In [46]:
fahrenheit = int(input("Enter the Fahrenheit: "))

def f_to_c(temperature):
    celsius = (temperature - 32) * 5/9
    print(f"Celsius is {celsius} when Fahrenheit is {temperature}")
    return celsius

result_celsius = f_to_c(fahrenheit)

Enter the Fahrenheit:  32


Celsius is 0.0 when Fahrenheit is 32


# Exercise 7 Numpy:

NumPy is a library for numerical operations in Python. NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices. NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.
 
* Import NumPy and create a 1D array with values 1 to 5. 
* Create a 2D array with random integers. 
* Perform element-wise multiplication of two arrays. 

In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [51]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

#Or what if we can use the random function:

array_2d = np.random.randint(0, 10, size=(3, 3))
print(array_2d)

[[1 2 3]
 [4 5 6]]
[[2 6 9]
 [7 9 2]
 [7 6 1]]


In [52]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)


40320


# Challenge 7:

Calculate the mean and standard deviation of elements in a NumPy array. The outcome should have something like ``print(f"Mean: {mean_value}, Standard Deviation: {std_deviation}")``

In [54]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
mean_value = np.mean(arr)
std_deviation = np.std(arr)

print(f"Mean: {mean_value}, Standard Deviation: {std_deviation}")

Mean: 3.5, Standard Deviation: 1.707825127659933


# Exercise 8: Pandas DataFrame

Pandas is a powerful data manipulation library.

* Create a DataFrame with a dictionary of student names and their marks.
* Add a new column for the grade based on the mark.
* Filter the DataFrame to show only students with scores above 80.
* Read a CSV file into a DataFrame and perform basic data exploration.

In [60]:
import pandas as pd

# Create a DataFrame with a dictionary of student names and their scores.
data = {"Student": ["Alice", "Bob", "Charlie"], "Mark": [85, 92, 78]} # Do you recall what a dictionary is???
df = pd.DataFrame(data)

# Add a new column for the grade based on the score using a loop.
grades = []
for score in df["Mark"]:
    if score >= 90:
        grades.append("A")
    elif score >= 80:
        grades.append("B")
    else:
        grades.append("C")

df["Grade"] = grades

# What if I can tell you there is a way you can avoid this long for loop, by using a function call lambda to run over each row in your dataframe., uncomment the following line and try that out.
# compare the results, and make sure you understand what the code is doing.
#df["Grade"] = df["Mark"].apply(lambda x: "A" if x >= 90 else "B" if x >= 80 else "C")


# Filter the DataFrame to show only students with scores above 80.
filtered_df = df[df["Mark"] > 80]

# Read a CSV file into a DataFrame and perform basic data exploration.
# There is a world_cities.csv in the Moodle folder, make sure you add that in the folder where you have this notebook/

csv_df = pd.read_csv('world_cities.csv')
print(csv_df.head())

                 city    country    pop    lat    lon  capital
0  'Abasan al-Jadidah  Palestine   5629  31.31  34.34        0
1  'Abasan al-Kabirah  Palestine  18999  31.32  34.35        0
2        'Abdul Hakim   Pakistan  47788  30.55  72.11        0
3  'Abdullah-as-Salam     Kuwait  21817  29.36  47.98        0
4               'Abud  Palestine   2456  32.03  35.07        0


# Challenge 8:

You have the following dataframes 'sales_data' and 'movie_ratings'


In [63]:
import pandas as pd

sales_data_dict = {
    'Date': ['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04'],
    'Region': ['North', 'South', 'East', 'West'],
    'Product': ['A', 'B', 'A', 'C'],
    'Quantity': [15, 8, 12, 10],
    'Revenue': [1500, 1200, 1800, 900]
}

sales_data = pd.DataFrame(sales_data_dict)


movie_ratings_dict = {
    'Title': ['Movie1', 'Movie2', 'Movie3', 'Movie4'],
    'Genre': ['Action', 'Drama', 'Comedy', 'Thriller'],
    'Year': [2015, 2010, 2018, 2011],
    'Rating': [8.5, 7.8, 9.2, 8.0]
}

movie_ratings = pd.DataFrame(movie_ratings_dict)

print(sales_data)
print(movie_ratings)


         Date Region Product  Quantity  Revenue
0  2022-01-01  North       A        15     1500
1  2022-01-02  South       B         8     1200
2  2022-01-03   East       A        12     1800
3  2022-01-04   West       C        10      900
    Title     Genre  Year  Rating
0  Movie1    Action  2015     8.5
1  Movie2     Drama  2010     7.8
2  Movie3    Comedy  2018     9.2
3  Movie4  Thriller  2011     8.0


* Display the first 5 rows of the DataFrame 'sales_data'
* Use `loc` to filter and display rows where the "Quantity" is greater than 10 and the "Region" is "North".
* Use `iloc` to display the values in the first row and the first three columns.
* Calculate the total sales for each region and display the result.

* Display the last 3 rows of the DataFrame 'movie_ratings'.
* Calculate and display the average rating for each genre.

In [65]:
print(sales_data.head)


<bound method NDFrame.head of          Date Region Product  Quantity  Revenue
0  2022-01-01  North       A        15     1500
1  2022-01-02  South       B         8     1200
2  2022-01-03   East       A        12     1800
3  2022-01-04   West       C        10      900>


In [68]:
df = sales_data 
filtered_data = df.loc[(df['Quantity'] > 10) & (df['Region'] == 'North')]
print(filtered_data)
first_row_first_three_columns = df.iloc[0,0:3]
print(first_row_first_three_columns)

         Date Region Product  Quantity  Revenue
0  2022-01-01  North       A        15     1500
Date       2022-01-01
Region          North
Product             A
Name: 0, dtype: object


In [70]:
df1 = movie_ratings
last_3_rows_df1 = df1.tail(3)
print(last_3_rows_df1)

    Title     Genre  Year  Rating
1  Movie2     Drama  2010     7.8
2  Movie3    Comedy  2018     9.2
3  Movie4  Thriller  2011     8.0


In [73]:
average_ratings = df1.groupby('Genre')['Rating'].mean()
print(average_ratings)

Genre
Action      8.5
Comedy      9.2
Drama       7.8
Thriller    8.0
Name: Rating, dtype: float64


# Exercise 9: GeoPandas and Rasterio:

GeoPandas deals with geospatial data, and Rasterio is used for working with raster data.

* Import GeoPandas and Rasterio libraries.
* Read a shapefile into a GeoDataFrame.
* Open and display a raster image using Rasterio.
* Let's recall how to perform a spatial join between a GeoDataFrame and a raster dataset.



In [ ]:
import geopandas as gpd
import rasterio
from rasterio.plot import show

shapefile_path = 'Road_Safety_Accidents.shp'
gdf = gpd.read_file(shapefile_path)
gdf.explore()

In [ ]:
raster_path = 'elev.tif'
raster = rasterio.open(raster_path)
show(raster)

# Challenge 9:

* Recreate the explore map, but now using one of the columns to create a choropleth map Check this link to get more information https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.explore.html

* Get the histogram of the raster you plot in the exercise. Here you can get an example of how to do it: https://rasterio.readthedocs.io/en/latest/topics/plotting.html


# Challenge 10: Last Mile

Now make sure you Jupyter Notebook includes all the outcomes from the Excersices and Challenges, make sure you comment all the code you had to add and make sure you describe what are you doing and make sure you have the correct outcomes. Finally pull all your changes  to your UA repo, in this case all your work is save in the cloud!